### ISSUE TITLE
FixedProbability Connections not being handled.

### ISSUE THREAD

**Issue by AdamRTomkins** [SpineML/SpineML_PreFlight#10]
Create an arbitrary connection between two populations and choose fixedprobability. SpineML_PreFlight will not expand the fixed prob.

Example model found at: https://bitbucket.org/AdamTomkins/spine_ml_translator

(Precisely, commit 74c46d7)

**Comment by sebjameswml** [comment]
Hi @AdamRTomkins any chance you can provide access to the spine_ml_translator directory? My bitbucket user is sebjames_shef. Cheers.

**Comment by sebjameswml** [comment]
Actually, don't worry - no real need; I can easily set up a dummy network to reproduce this.

**Comment by sebjameswml** [comment]
Fixed with 3596a72
