### ISSUE TITLE
delay flag not being read when preflighting generic connections

### ISSUE THREAD

**Issue by sebjameswml** [SpineML/SpineML_PreFlight#12]
Such as in @TACD's model. Alex C has more info.

**Comment by TACD** [comment]
Not sure if this is important, but I tried making an explicit connection list without a 'delay' column (forcing SpineCreator to fall back on the built-in delay tool) and the issue persists.

**Comment by sebjameswml** [comment]
@ajc158 tracked this down to being a problem in SpineML_2_BRAHMS. See commit a09315ba9 there

**Comment by sebjameswml** [comment]
Could change SpineML_PreFlight to complain if there are delays in a generic input, because these are not honoured by SpineML_2_BRAHMS. (Take note @TACD ) Agree @ajc18?

**Comment by TACD** [comment]
That could well be the source of my repeated "Only Fixed delays for generic inputs currently supported for BRAHMS" errors then...

Also:
Compiling for Linux
component.cpp: In member function ‘virtual brahms::Symbol dev_spineml_tools_explicitlist_0::event(brahms::Event*)’:
component.cpp:138:6: error: ‘delayForConnTemp’ was not declared in this scope
      delayForConnTemp.resize(_num_conn);
      ^
component.cpp:153:14: error: ‘delayForConnTemp’ was not declared in this scope
       fread(&delayForConnTemp[i_BRAHMS], sizeof(unsigned int), 1, binfile);
              ^
component.cpp:175:8: error: ‘_has_delay’ was not declared in this scope
    if (_has_delay) {
        ^

**Comment by sebjameswml** [comment]
This is not a SpineML_PreFlight issue and it's now fixed in SpineML_2_BRAHMS>
