### ISSUE TITLE
Preflight does not expand state variables on weight updates correctly

### ISSUE THREAD

**Issue by ajc158** [SpineML/SpineML_PreFlight#6]
The Preflight tool does not extract the dimensionality of the state variables on a weight update correctly - it expands the SV to (for example) 100 values when the projection is 10 -> 10000 all to all!

**Comment by sebjameswml** [comment]
Hi Alex, have you got a sample project which shows this problem, and can you share that with me so I can reproduce?

**Comment by ajc158** [comment]
Here you go:

If you have a look at the preflighted 'w' state variable it should be the
wrong size

On 12 August 2015 at 14:32, Seb James <notifications@github.com> wrote:

> Hi Alex, have you got a sample project which shows this problem, and can
> you share that with me so I can reproduce?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SpineML/SpineML_PreFlight/issues/6#issuecomment-130303055>
> .
>



-- 
Alex Cope
Research Associate
Behavioural and Evolutionary Theory Lab
Department of Computer Science, University of Sheffield
www.alexcope.co.uk

**Comment by sebjameswml** [comment]
There doesn't seem to be an attachment either here in github or in the email. You might need to send a non-github related email?

**Comment by sebjameswml** [comment]
Hopefully fixed with commit dff1ba4 in master. Alex, can you check?

**Comment by ajc158** [comment]
Looks good - certainly runs and has the right dimensionality!

On 12 August 2015 at 15:28, Seb James <notifications@github.com> wrote:

> Hopefully fixed with commit dff1ba4
> <https://github.com/SpineML/SpineML_PreFlight/commit/dff1ba48b7ad3f2cbc81ce4deed12defc897064f>
> in master. Alex, can you check?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SpineML/SpineML_PreFlight/issues/6#issuecomment-130321775>
> .
>



-- 
Alex Cope
Research Associate
Behavioural and Evolutionary Theory Lab
Department of Computer Science, University of Sheffield
www.alexcope.co.uk

**Comment by sebjameswml** [comment]
I'm fairly sure it now does what it's supposed to do - just duplicate the fixed value into a many-valued explicitDataBinaryFile, so I'll close this now.
