### ISSUE TITLE
Preflight doesn't work with SpikeSources

### ISSUE THREAD

**Issue by ajc158** [SpineML/SpineML_PreFlight#7]
Preflight throws an error when you try to include a SpikeSource in the model - says it can't find a delay

**Comment by sebjameswml** [comment]
Interesting. I have one model which contains spike sources and that is ok. I'll email you that model; can you email me your one which doesn't work?

**Comment by sebjameswml** [comment]
The code for reading an XML specified ConnectionList was expecting this from the model:
```
                <ConnectionList>
                    <Connection src_neuron="0" dst_neuron="5" delay="1"/>
                    <Connection src_neuron="0" dst_neuron="8" delay="1"/>
```
(note the explicit delay attributes).

It was failing to handle a ConnectionList with an overall Delay element for all the connections like this:
```
                <ConnectionList>
                    <Connection src_neuron="0" dst_neuron="5"/>
                    <Connection src_neuron="0" dst_neuron="8"/>
                    <Connection src_neuron="0" dst_neuron="40"/>
                    [snip more Connection lines]
                    <Delay Dimension="ms">
                        <FixedValue value="0"/>
                    </Delay>
                </ConnectionList>
```

Commit b77e681 resolves this.

**Comment by sebjameswml** [comment]
@ajc158 could you check if your model will run now? Ta.

**Comment by ajc158** [comment]
All good, thanks!

On 14 August 2015 at 12:01, Seb James <notifications@github.com> wrote:

> @ajc158 <https://github.com/ajc158> could you check if your model will
> run now? Ta.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SpineML/SpineML_PreFlight/issues/7#issuecomment-131077798>
> .
>



-- 
Alex Cope
Research Associate
Behavioural and Evolutionary Theory Lab
Department of Computer Science, University of Sheffield
www.alexcope.co.uk

**Comment by sebjameswml** [comment]
Grand. Closing this issue.
