### ISSUE TITLE
Fixed probability connections need packed_data="true" attribute after expansion to explicit lists

### ISSUE THREAD

**Issue by ajc158** [SpineML/SpineML_PreFlight#8]
In order to read models back into SpineCreator (e.g. for learning) the ConnectionLists instantiated from Fixed Probability connections need to have an attribute packed_data="true".

**Comment by sebjameswml** [comment]
What does packed_data signify? Are there any cases where it should be omitted?

**Comment by ajc158** [comment]
packed_data signifies that the data is not output using the Qt
serialisation streams. Basically it is in full use at the moment apart from
to support legacy models. In time it can be phased out.

On 14 August 2015 at 13:57, Seb James <notifications@github.com> wrote:

> What does packed_data signify? Are there any cases where it should be
> omitted?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SpineML/SpineML_PreFlight/issues/8#issuecomment-131097395>
> .
>



-- 
Alex Cope
Research Associate
Behavioural and Evolutionary Theory Lab
Department of Computer Science, University of Sheffield
www.alexcope.co.uk

**Comment by sebjameswml** [comment]
Ok, I'll add it in. Are there any other uses of packed_data, other than in ConnectionLists?

**Comment by sebjameswml** [comment]
packed_data attribute added for ConnectionLists in commit 4d70895

**Comment by ajc158** [comment]
Nope

On 14 August 2015 at 14:04, Seb James <notifications@github.com> wrote:

> packed_data attribute added for ConnectionLists in commit 4d70895
> <https://github.com/SpineML/SpineML_PreFlight/commit/4d70895110eea5cda564f7b5bbf3e8a19031b1ef>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SpineML/SpineML_PreFlight/issues/8#issuecomment-131098976>
> .
>



-- 
Alex Cope
Research Associate
Behavioural and Evolutionary Theory Lab
Department of Computer Science, University of Sheffield
www.alexcope.co.uk
